use customer_behaviour;
show databases;
select * from customer_data;
RENAME TABLE customer_data TO customer;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
      );
      
-- Q3 which are the top five products with the highest averrage review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4 Compare the average purchase amount between the standard and express shipping.

SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? compare average spend and total revenue 
-- between subscribers and non-subscribers

SELECT 
    subscription_status,
    COUNT(customer_id) AS `total customers`,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS `total revenue`
FROM customer
GROUP BY subscription_status;

-- Q6 which 5 products have the highest percentage of purchases with discount applied?

SELECT 
    item_purchased,
    ROUND(
        SUM(CASE 
                WHEN discount_applied = 'Yes' THEN 1 
                ELSE 0 
            END) / COUNT(*) * 100
    , 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 18 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment 
    FROM customer
)

SELECT 
    customer_segment,
    COUNT(*) AS `Number of customers`
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM product_counts
WHERE rn <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(*) AS total_customers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

SELECT @@port;

















